# Generated by Django 6.0.5 on 2026-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='forms',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='forms',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='forms',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='forms',
            name='regno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='forms',
            name='skills',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='forms',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
